# Generated by Django 3.1.2 on 2020-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluserresponse',
            name='field_ml_prediction',
            field=models.IntegerField(help_text='Actual ML prediction'),
        ),
        migrations.AlterField(
            model_name='modeluserresponse',
            name='field_user_did_update',
            field=models.IntegerField(help_text='Whether or not user updated the model'),
        ),
        migrations.AlterField(
            model_name='modeluserresponse',
            name='field_user_prediction',
            field=models.IntegerField(help_text='User prediction'),
        ),
    ]
